# Generated by Django 2.1.3 on 2018-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobentry',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='response',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobentry',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
