# Generated by Django 2.1.3 on 2018-11-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181105_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobentry',
            name='response',
            field=models.IntegerField(choices=[(1, 'No Response'), (2, 'Interviewing'), (3, 'Offer Received'), (4, 'Rejected')], default=1),
        ),
    ]
