# Generated by Django 2.1.3 on 2018-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181108_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobentry',
            name='response',
            field=models.IntegerField(choices=[(1, 'No Response'), (2, 'Offer Received'), (3, 'Interviewing'), (4, 'Rejected')], default=1),
        ),
    ]
